// TypeScript declarations for one program, from its caveat-interface/0.1
// interface (spec/caveat-interface-0.1.md), and typed() to use them with a
// session. The declarations are types only: they change nothing a session does.

export const INTERFACE_SCHEMA = 'caveat-interface/0.1';

const quote = name => JSON.stringify(name);
const union = names => (names.length ? names.map(quote).join(' | ') : 'never');
const key = name => (/^[A-Za-z_$][\w$]*$/.test(name) ? name : quote(name));

function payloadField(parameter) {
  switch (parameter.type) {
    case 'number': return 'number';
    case 'id': return 'string';
    case 'entity':
    case 'member': return union(parameter.members);
    default: throw new Error(`parameter ${parameter.name} has an unknown type ${parameter.type}`);
  }
}

const VALUE_TYPES = { number: 'number', boolean: 'boolean', text: 'string' };

// The text of a .d.ts module. program names the source in its header; from is
// the module specifier the declarations import the session types from.
export function declarations(programInterface, { program = 'the program', from = 'caveat-lang/types' } = {}) {
  if (programInterface?.schema !== INTERFACE_SCHEMA) {
    throw new Error(`expected a ${INTERFACE_SCHEMA} interface, found ${JSON.stringify(programInterface?.schema)}`);
  }
  const { events, states, bindings, cues, decisions, readings, evidence, caveats, claims } = programInterface;
  const lines = [
    `// Declarations for ${program}, generated by \`caveat types\` from its`,
    `// ${INTERFACE_SCHEMA} interface. Regenerate them when the program changes.`,
    `import type { TypedSession, TypedView } from ${quote(from)};`,
    '',
    '/** What the program accepts and shows. */',
    'export interface Program {',
    '  /** Each event\'s JSON payload. An entity or member is sent by name. */',
    '  events: {',
  ];
  for (const event of events) {
    const fields = event.parameters.map(parameter => `${key(parameter.name)}: ${payloadField(parameter)}`);
    lines.push(`    ${key(event.name)}: ${fields.length ? `{ ${fields.join('; ')} }` : 'Record<string, never>'};`);
  }
  lines.push('  };');
  lines.push('  /** Displayed values by target and property; an optional one is shown only while a condition holds. */');
  lines.push('  bindings: {');
  const targets = new Map();
  for (const binding of bindings) {
    if (!targets.has(binding.target)) targets.set(binding.target, []);
    targets.get(binding.target).push(`${key(binding.property)}${binding.always ? '' : '?'}: ${VALUE_TYPES[binding.type]}`);
  }
  for (const [target, properties] of targets) lines.push(`    ${key(target)}: { ${properties.join('; ')} };`);
  lines.push('  };');
  lines.push('}');
  lines.push('');
  const names = (alias, list, what) => {
    lines.push(`/** ${what} */`);
    lines.push(`export type ${alias} = ${union(list)};`);
  };
  lines.push('export type EventName = keyof Program[\'events\'];');
  lines.push('/** One event as a host might queue it. */');
  lines.push('export type ProgramEvent = { [K in EventName]: { event: K; payload: Program[\'events\'][K] } }[EventName];');
  lines.push('export type Bindings = Program[\'bindings\'];');
  names('StateName', states.map(state => state.name), 'States, by name.');
  names('CueName', cues.map(cue => cue.name), 'Declared cues.');
  names('DecisionName', decisions.map(series => series.name), 'Decision series; a revision is `NAME@N`.');
  names('ReadingsName', readings.map(stream => stream.name), 'Reading streams; a reading is `NAME@N`.');
  names('EvidenceName', evidence, 'Declared evidence; a renewed occurrence is `NAME@N`.');
  names('CaveatName', caveats, 'Declared caveats.');
  names('ClaimName', claims, 'Declared claims.');
  lines.push('');
  lines.push('/** A session of this program: `typed<Program>(runtime.open(source))`. */');
  lines.push('export type Session = TypedSession<Program>;');
  lines.push('export type View = TypedView<Program>;');
  return `${lines.join('\n')}\n`;
}

// The session itself, unchanged. Its declared type takes the program's
// declarations, so a checker sees the program's event names, payloads and
// bindings.
export function typed(session) {
  return session;
}
