pub mod ast; pub mod parser; pub mod eval;
use std::collections::HashMap; pub type NodeId=u64;
#[derive(Debug,Clone,Copy,PartialEq,Eq,PartialOrd,Ord)]pub enum Consequence{Negligible,Low,Material,High,Catastrophic}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum Attention{Unexamined,Deferred,Examining,Examined}
#[derive(Debug,Clone,PartialEq,Eq)]pub enum StopReason{Enough,BudgetExhausted,Deadline,ExternalDecision(String)}
#[derive(Debug,Clone,PartialEq,Eq)]pub enum NodeKind{Claim{proposition:String},Evidence{description:String,source:String},Caveat{description:String,consequence:Consequence,attention:Attention},Context{name:String},Commitment{action:String,open:bool,stop_reason:StopReason},Observation{description:String}}
#[derive(Debug,Clone,Copy,PartialEq,Eq)]pub enum Relation{Supports,Opposes,Qualifies,InContext,Retains,Reopens}
#[derive(Debug,Clone,PartialEq,Eq)]pub struct Edge{pub from:NodeId,pub to:NodeId,pub relation:Relation}
#[derive(Debug,Default)]pub struct EpistemicGraph{next_id:NodeId,pub nodes:HashMap<NodeId,NodeKind>,pub edges:Vec<Edge>}
impl EpistemicGraph{pub fn new()->Self{Self{next_id:1,..Self::default()}} pub fn add(&mut self,n:NodeKind)->NodeId{let i=self.next_id;self.next_id+=1;self.nodes.insert(i,n);i} pub fn add_caveat(&mut self,d:impl Into<String>,c:Consequence)->NodeId{self.add(NodeKind::Caveat{description:d.into(),consequence:c,attention:Attention::Unexamined})} pub fn relate(&mut self,f:NodeId,r:Relation,t:NodeId){assert!(self.nodes.contains_key(&f));assert!(self.nodes.contains_key(&t));self.edges.push(Edge{from:f,to:t,relation:r})} pub fn set_attention(&mut self,c:NodeId,a:Attention){match self.nodes.get_mut(&c){Some(NodeKind::Caveat{attention,..})=>*attention=a,_=>panic!("attention target must be a caveat")}} pub fn consequence(&self,c:NodeId)->Consequence{match self.nodes.get(&c){Some(NodeKind::Caveat{consequence,..})=>*consequence,_=>panic!("consequence target must be a caveat")}} pub fn commit(&mut self,a:impl Into<String>,r:&[NodeId])->NodeId{self.commit_because(a,r,StopReason::Enough)} pub fn commit_because(&mut self,a:impl Into<String>,r:&[NodeId],s:StopReason)->NodeId{let i=self.add(NodeKind::Commitment{action:a.into(),open:false,stop_reason:s});for &n in r{self.relate(i,Relation::Retains,n)}i} pub fn reopen(&mut self,c:NodeId,b:NodeId){match self.nodes.get_mut(&c){Some(NodeKind::Commitment{open,..})=>*open=true,_=>panic!("reopen target must be a commitment")};self.relate(b,Relation::Reopens,c)} pub fn relations(&self,r:Relation)->impl Iterator<Item=&Edge>{self.edges.iter().filter(move|e|e.relation==r)} pub fn qualification_depth_from(&self,root:NodeId)->usize{fn d(g:&EpistemicGraph,n:NodeId,p:&mut Vec<NodeId>)->usize{if p.contains(&n){return 0}p.push(n);let m=g.edges.iter().filter(|e|e.relation==Relation::Qualifies&&e.to==n).map(|e|1+d(g,e.from,p)).max().unwrap_or(0);p.pop();m}d(self,root,&mut vec![])}}
#[cfg(test)]mod tests{use super::*;
#[test]fn source_to_graph(){let p=parser::parse("claim r; caveat e1 consequence low; caveat e2 consequence low; e1 qualifies r; e2 qualifies e1; commit ship because enough retaining e1, e2;").unwrap();let x=eval::evaluate(&p).unwrap();assert_eq!(x.graph.qualification_depth_from(x.symbols["r"]),2);}
#[test]fn qualification_cycle_terminates(){let p=parser::parse("caveat a consequence material; caveat b consequence material; a qualifies b; b qualifies a;").unwrap();let x=eval::evaluate(&p).unwrap();let depth=x.graph.qualification_depth_from(x.symbols["a"]);assert!(depth>0&&depth<10);}
#[test]fn contradictory_evidence_coexists(){let p=parser::parse("claim door; evidence camera from cam; evidence latch from sensor; camera supports door; latch opposes door;").unwrap();let x=eval::evaluate(&p).unwrap();let door=x.symbols["door"];assert_eq!(x.graph.edges.iter().filter(|e|e.to==door&&matches!(e.relation,Relation::Supports|Relation::Opposes)).count(),2);}
#[test]fn duplicate_symbol_fails(){let p=parser::parse("claim x; claim x;").unwrap();assert!(eval::evaluate(&p).unwrap_err().contains("duplicate symbol"));}
#[test]fn unknown_symbol_fails(){let p=parser::parse("claim x; ghost supports x;").unwrap();assert!(eval::evaluate(&p).unwrap_err().contains("unknown symbol"));}
#[test]fn repeated_reopen_is_visible_history(){let p=parser::parse("claim x; caveat c consequence material; commit go because enough retaining c; reopen go because c; reopen go because c;").unwrap();let x=eval::evaluate(&p).unwrap();let go=x.symbols["go"];assert_eq!(x.graph.relations(Relation::Reopens).filter(|e|e.to==go).count(),2);}
}
