use crate::ast::{Program,Statement};use crate::eval::EventKind;
#[derive(Debug,Clone,PartialEq,Eq)]pub enum PendingInteraction{Investigate{name:String,options:Vec<String>,cost:u64,budget:u64},Choice{name:String,options:Vec<String>,budget:u64},Complete}
#[derive(Debug,Clone,PartialEq,Eq)]pub struct Discovery{pub because:String,pub evidence:String,pub relation:String,pub target:String}
#[derive(Debug,Clone,PartialEq,Eq)]pub struct CommitmentFeedback{pub action:String,pub retained:Vec<String>,pub reopened_by:Vec<String>}
#[derive(Debug,Clone)]pub struct Session{program:Program,cursor:usize,last_discoveries:Vec<Discovery>,last_commitment:Option<CommitmentFeedback>}
impl Session{pub fn from_source(source:&str)->Result<Self,String>{Ok(Self{program:crate::parser::parse(source)?,cursor:0,last_discoveries:vec![],last_commitment:None})}
pub fn pending(&self)->Result<PendingInteraction,String>{for i in self.cursor..self.program.statements.len(){match &self.program.statements[i]{Statement::Inspect{investigation,cost,..}=>{let e=crate::eval::evaluate(&Program::new(self.program.statements[..i].to_vec()))?;let inv=e.investigations.get(investigation).ok_or_else(||format!("unknown investigation: {investigation}"))?;return Ok(PendingInteraction::Investigate{name:investigation.clone(),options:inv.options.clone(),cost:*cost,budget:e.resources.as_ref().map(|b|b.remaining).unwrap_or(0)})},Statement::Select{choice,..}=>{let e=crate::eval::evaluate(&Program::new(self.program.statements[..i].to_vec()))?;let cp=e.choices.get(choice).ok_or_else(||format!("unknown choice: {choice}"))?;return Ok(PendingInteraction::Choice{name:choice.clone(),options:cp.options.clone(),budget:e.resources.as_ref().map(|b|b.remaining).unwrap_or(0)})},_=>{}}}Ok(PendingInteraction::Complete)}
pub fn apply(&mut self,selection:&str)->Result<(),String>{self.last_discoveries.clear();self.last_commitment=None;let i=(self.cursor..self.program.statements.len()).find(|&i|matches!(self.program.statements[i],Statement::Inspect{..}|Statement::Select{..})).ok_or("session is complete")?;let prefix=crate::eval::evaluate(&Program::new(self.program.statements[..i].to_vec()))?;match self.program.statements[i].clone(){Statement::Inspect{investigation,..}=>{let inv=prefix.investigations.get(&investigation).ok_or("unknown investigation")?;if !inv.options.iter().any(|x|x==selection){return Err(format!("invalid investigation selection: {selection}"))}if let Statement::Inspect{caveat,..}=&mut self.program.statements[i]{*caveat=selection.into();}},Statement::Select{choice,..}=>{let cp=prefix.choices.get(&choice).ok_or("unknown choice")?;if !cp.options.iter().any(|x|x==selection){return Err(format!("invalid choice selection: {selection}"))}if let Statement::Select{option,..}=&mut self.program.statements[i]{*option=selection.into();}},_=>unreachable!()}let next=(i+1..self.program.statements.len()).find(|&j|matches!(self.program.statements[j],Statement::Inspect{..}|Statement::Select{..})).unwrap_or(self.program.statements.len());let e=crate::eval::evaluate(&Program::new(self.program.statements[..next].to_vec()))?;let name=|id|e.symbols.iter().find_map(|(n,v)|if *v==id{Some(n.clone())}else{None}).unwrap_or_else(||id.to_string());let mut committed_id=None;for ev in &e.history{match &ev.kind{EventKind::Revealed{because,from,relation,to}=>self.last_discoveries.push(Discovery{because:name(*because),evidence:name(*from),relation:format!("{:?}",relation).to_lowercase(),target:name(*to)}),EventKind::Committed{commitment,retained,..}if name(*commitment)==selection=>{committed_id=Some(*commitment);self.last_commitment=Some(CommitmentFeedback{action:selection.into(),retained:retained.iter().map(|x|name(*x)).collect(),reopened_by:vec![]})},_=>{}}}if let(Some(id),Some(f))=(committed_id,self.last_commitment.as_mut()){for ev in &e.history{if let EventKind::Reopened{commitment,because}=ev.kind{if commitment==id{f.reopened_by.push(name(because));}}}}self.cursor=i+1;Ok(())}
pub fn discoveries(&self)->&[Discovery]{&self.last_discoveries}pub fn commitment(&self)->Option<&CommitmentFeedback>{self.last_commitment.as_ref()}pub fn program(&self)->&Program{&self.program}}
