use std::fmt::Write as _;

#[derive(Debug,Clone,Copy,PartialEq)]pub struct Vec3{pub x:f32,pub y:f32,pub z:f32}impl Vec3{pub const fn new(x:f32,y:f32,z:f32)->Self{Self{x,y,z}}}
#[derive(Debug,Clone,Copy,PartialEq)]pub struct Transform3D{pub position:Vec3,pub rotation:Vec3,pub scale:Vec3}impl Transform3D{pub const fn new(position:Vec3,rotation:Vec3,scale:Vec3)->Self{Self{position,rotation,scale}}}
#[derive(Debug,Clone,PartialEq)]pub struct Camera3D{pub id:String,pub transform:Transform3D,pub fov:f32}
#[derive(Debug,Clone,PartialEq)]pub enum Primitive3D{Box,Plane,Sphere}
#[derive(Debug,Clone,PartialEq)]pub struct Object3D{pub id:String,pub primitive:Primitive3D,pub transform:Transform3D,pub interactive:Option<String>}
#[derive(Debug,Clone,PartialEq)]pub enum LightKind3D{Point,Directional,Ambient}
#[derive(Debug,Clone,PartialEq)]pub struct Light3D{pub id:String,pub kind:LightKind3D,pub position:Vec3,pub intensity:f32}
#[derive(Debug,Clone,PartialEq)]pub enum WorldEvent3D{RotateY{object:String,degrees:f32,duration:f32},MoveTo{object:String,position:Vec3,duration:f32},SetVisible{object:String,visible:bool}}
#[derive(Debug,Clone,PartialEq)]pub struct World3D{pub id:String,pub camera:Camera3D,pub objects:Vec<Object3D>,pub lights:Vec<Light3D>,pub events:Vec<WorldEvent3D>}
impl World3D{pub fn the_door()->Self{let t=|p,s|Transform3D::new(p,Vec3::new(0.,0.,0.),s);Self{id:"evacuation_corridor".into(),camera:Camera3D{id:"player".into(),transform:t(Vec3::new(0.,1.7,5.),Vec3::new(1.,1.,1.)),fov:70.},objects:vec![Object3D{id:"floor".into(),primitive:Primitive3D::Box,transform:t(Vec3::new(0.,-.1,0.),Vec3::new(8.,.2,18.)),interactive:None},Object3D{id:"door".into(),primitive:Primitive3D::Box,transform:t(Vec3::new(0.,1.2,-4.),Vec3::new(2.2,2.4,.2)),interactive:Some("open".into())},Object3D{id:"latch".into(),primitive:Primitive3D::Box,transform:t(Vec3::new(1.,1.2,-3.8),Vec3::new(.15,.25,.12)),interactive:Some("latch_sensor_recently_serviced".into())},Object3D{id:"security_camera".into(),primitive:Primitive3D::Box,transform:t(Vec3::new(-2.5,2.6,-2.),Vec3::new(.3,.2,.5)),interactive:Some("camera_has_blind_spot".into())},Object3D{id:"stairwell".into(),primitive:Primitive3D::Box,transform:t(Vec3::new(3.,1.,-7.),Vec3::new(2.,2.,.2)),interactive:Some("stairwell".into())}],lights:vec![Light3D{id:"emergency".into(),kind:LightKind3D::Point,position:Vec3::new(0.,2.7,1.),intensity:.8},Light3D{id:"ambient".into(),kind:LightKind3D::Ambient,position:Vec3::new(0.,0.,0.),intensity:.18}],events:vec![]}}
pub fn apply_action(&mut self,action:&str,reopened:bool){match action{"open"=>self.events.push(WorldEvent3D::RotateY{object:"door".into(),degrees:90.,duration:1.2}),"stairwell"=>self.events.push(WorldEvent3D::MoveTo{object:"player".into(),position:Vec3::new(3.,1.7,-6.),duration:1.5}),"retreat"=>self.events.push(WorldEvent3D::MoveTo{object:"player".into(),position:Vec3::new(0.,1.7,7.),duration:1.2}),_=>{}}if reopened{self.events.push(WorldEvent3D::SetVisible{object:"reopened_marker".into(),visible:true});}}
pub fn to_json(&self)->String{format!("{{\"schema\":1,\"id\":{},\"camera\":{},\"objects\":[{}],\"lights\":[{}],\"events\":[{}]}}",js(&self.id),camera_json(&self.camera),self.objects.iter().map(object_json).collect::<Vec<_>>().join(","),self.lights.iter().map(light_json).collect::<Vec<_>>().join(","),self.events.iter().map(event_json).collect::<Vec<_>>().join(","))}}
fn v(v:Vec3)->String{format!("[{:?},{:?},{:?}]",v.x,v.y,v.z)}fn tr(t:Transform3D)->String{format!("{{\"position\":{},\"rotation\":{},\"scale\":{}}}",v(t.position),v(t.rotation),v(t.scale))}fn primitive(p:&Primitive3D)->&'static str{match p{Primitive3D::Box=>"box",Primitive3D::Plane=>"plane",Primitive3D::Sphere=>"sphere"}}fn camera_json(c:&Camera3D)->String{format!("{{\"id\":{},\"transform\":{},\"fov\":{:?}}}",js(&c.id),tr(c.transform),c.fov)}fn object_json(o:&Object3D)->String{format!("{{\"id\":{},\"primitive\":{},\"transform\":{},\"interactive\":{}}}",js(&o.id),js(primitive(&o.primitive)),tr(o.transform),o.interactive.as_ref().map(|x|js(x)).unwrap_or_else(||"null".into()))}fn light_json(l:&Light3D)->String{let k=match l.kind{LightKind3D::Point=>"point",LightKind3D::Directional=>"directional",LightKind3D::Ambient=>"ambient"};format!("{{\"id\":{},\"kind\":{},\"position\":{},\"intensity\":{:?}}}",js(&l.id),js(k),v(l.position),l.intensity)}fn event_json(e:&WorldEvent3D)->String{match e{WorldEvent3D::RotateY{object,degrees,duration}=>format!("{{\"kind\":\"rotate_y\",\"object\":{},\"degrees\":{:?},\"duration\":{:?}}}",js(object),degrees,duration),WorldEvent3D::MoveTo{object,position,duration}=>format!("{{\"kind\":\"move_to\",\"object\":{},\"position\":{},\"duration\":{:?}}}",js(object),v(*position),duration),WorldEvent3D::SetVisible{object,visible}=>format!("{{\"kind\":\"visible\",\"object\":{},\"visible\":{}}}",js(object),visible)}}fn js(s:&str)->String{let mut o=String::from("\"");for c in s.chars(){match c{'"'=>o.push_str("\\\""),'\\'=>o.push_str("\\\\"),'\n'=>o.push_str("\\n"),c if c.is_control()=>{let _=write!(o,"\\u{:04x}",c as u32);},c=>o.push(c)}}o.push('"');o}
#[cfg(test)]mod tests{use super::*;#[test]fn door_world_has_interactions(){let w=World3D::the_door();assert_eq!(w.objects.iter().find(|o|o.id=="security_camera").unwrap().interactive.as_deref(),Some("camera_has_blind_spot"));assert!(w.to_json().contains("evacuation_corridor"));}#[test]fn open_emits_door_rotation(){let mut w=World3D::the_door();w.apply_action("open",true);assert!(matches!(w.events[0],WorldEvent3D::RotateY{ref object,..}if object=="door"));assert_eq!(w.events.len(),2);}}
