// Declarations for gauge.cav, generated by `caveat types` from its
// caveat-interface/0.1 interface. Regenerate them when the program changes.
import type { TypedSession, TypedView } from "../lib/types.mjs";

/** What the program accepts and shows. */
export interface Program {
  /** Each event's JSON payload. An entity or member is sent by name. */
  events: {
    decide: Record<string, never>;
    pick: { bed: "north" | "south"; size: "small" | "large"; who: string };
    read: { celsius: number };
  };
  /** Displayed values by target and property; an optional one is shown only while a condition holds. */
  bindings: {
    gauge: { covered: boolean; label?: string; value: number };
  };
}

export type EventName = keyof Program['events'];
/** One event as a host might queue it. */
export type ProgramEvent = { [K in EventName]: { event: K; payload: Program['events'][K] } }[EventName];
export type Bindings = Program['bindings'];
/** States, by name. */
export type StateName = "level";
/** Declared cues. */
export type CueName = never;
/** Decision series; a revision is `NAME@N`. */
export type DecisionName = "cover";
/** Reading streams; a reading is `NAME@N`. */
export type ReadingsName = "soil";
/** Declared evidence; a renewed occurrence is `NAME@N`. */
export type EvidenceName = "probe";
/** Declared caveats. */
export type CaveatName = never;
/** Declared claims. */
export type ClaimName = "frost_risk";

/** A session of this program: `typed<Program>(runtime.open(source))`. */
export type Session = TypedSession<Program>;
export type View = TypedView<Program>;
